export const KORISNIK_LOGIN_REQUEST = 'KORISNIK_LOGIN_REQUEST'
export const KORISNIK_LOGIN_SUCCESS = 'KORISNIK_LOGIN_SUCESS'
export const KORISNIK_LOGIN_FAIL = 'KORISNIK_LOGIN_FAIL'
export const KORISNIK_LOGOUT = 'KORISNIK_LOGOUT'

export const KORISNIK_REGISTRIRAJ_REQUEST = 'KORISNIK_REGISTRIRAJ_REQUEST'
export const KORISNIK_REGISTRIRAJ_SUCCESS = 'KORISNIK_REGISTRIRAJ_SUCESS'
export const KORISNIK_REGISTRIRAJ_FAIL = 'KORISNIK_REGISTRIRAJ_FAIL'

export const KORISNIK_DETALJI_REQUEST = 'KORISNIK_DETALJI_REQUEST'
export const KORISNIK_DETALJI_SUCCESS = 'KORISNIK_DETALJI_SUCESS'
export const KORISNIK_DETALJI_FAIL = 'KORISNIK_DETALJI_FAIL'
export const KORISNIK_DETALJI_RESET = 'KORISNIK_DETALJI_RESET'


export const KORISNIK_AZURIRAJ_PROFIL_REQUEST = 'KORISNIK_AZURIRAJ_PROFIL_REQUEST'
export const KORISNIK_AZURIRAJ_PROFIL_SUCCESS = 'KORISNIK_AZURIRAJ_PROFIL_SUCESS'
export const KORISNIK_AZURIRAJ_PROFIL_FAIL = 'KORISNIK_AZURIRAJ_PROFIL_FAIL'
export const KORISNIK_AZURIRAJ_PROFIL_RESET = 'KORISNIK_AZURIRAJ_PROFIL_RESET'


export const KORISNIK_LIST_REQUEST = 'KORISNIK_LIST_REQUEST'
export const KORISNIK_LIST_SUCCESS = 'KORISNIK_LIST_SUCESS'
export const KORISNIK_LIST_FAIL = 'KORISNIK_LIST_FAIL'
export const KORISNIK_LIST_RESET = 'KORISNIK_LIST_RESET'


export const KORISNIK_DELETE_REQUEST = 'KORISNIK_DELETE_REQUEST'
export const KORISNIK_DELETE_SUCCESS = 'KORISNIK_DELETE_SUCESS'
export const KORISNIK_DELETE_FAIL = 'KORISNIK_DELETE_FAIL'

export const KORISNIK_AZURIRAJ_REQUEST = 'KORISNIK_AZURIRAJ_REQUEST'
export const KORISNIK_AZURIRAJ_SUCCESS = 'KORISNIK_AZURIRAJ_SUCESS'
export const KORISNIK_AZURIRAJ_FAIL = 'KORISNIK_AZURIRAJ_FAIL'
export const KORISNIK_AZURIRAJ_RESET = 'KORISNIK_AZURIRAJ_RESET'