export const KORPA_DODAJ_STAVKU = 'KORPA_DODAJ_STAVKU'
export const KORPA_UKLONI_STAVKU = 'KORPA_UKLONI_STAVKU'
export const KORPA_SACUVAJ_ADRESU_POSTARINE = 'KORPA_SACUVAJ_ADRESU_POSTARINE'
export const KORPA_SACUVAJ_METODU_PLACANJA = 'KORPA_SACUVAJ_METODU_PLACANJA'