export const NARUDZBA_KREIRAJ_REQUEST = 'NARUDZBA_KREIRAJ_REQUEST'
export const NARUDZBA_KREIRAJ_SUCCESS = 'NARUDZBA_KREIRAJ_SUCCESS'
export const NARUDZBA_KREIRAJ_FAIL = 'NARUDZBA_KREIRAJ_FAIL'


export const NARUDZBA_DETALJI_REQUEST = 'NARUDZBA_DETALJI_REQUEST'
export const NARUDZBA_DETALJI_SUCCESS = 'NARUDZBA_DETALJI_SUCCESS'
export const NARUDZBA_DETALJI_FAIL = 'NARUDZBA_DETALJI_FAIL'


export const NARUDZBA_PLATI_REQUEST = 'NARUDZBA_PLATI_REQUEST'
export const NARUDZBA_PLATI_SUCCESS = 'NARUDZBA_PLATI_SUCCESS'
export const NARUDZBA_PLATI_FAIL = 'NARUDZBA_PLATI_FAIL'
export const NARUDZBA_PLATI_RESET = 'NARUDZBA_PLATI_RESET'



export const MOJA_NARUDZBA_REQUEST = 'MOJA_NARUDZBA_REQUEST'
export const MOJA_NARUDZBA_SUCCESS = 'MOJA_NARUDZBA_SUCCESS'
export const MOJA_NARUDZBA_FAIL = 'MOJA_NARUDZBA_FAIL'
export const MOJA_NARUDZBA_RESET = 'MOJA_NARUDZBA_RESET'


export const NARUDZBE_LIST_REQUEST = 'NARUDZBE_LIST_REQUEST'
export const NARUDZBE_LIST_SUCCESS = 'NARUDZBE_LIST_SUCCESS'
export const NARUDZBE_LIST_FAIL = 'NARUDZBE_LIST_FAIL'


export const NARUDZBA_DOSTAVI_REQUEST = 'NARUDZBA_DOSTAVI_REQUEST'
export const NARUDZBA_DOSTAVI_SUCCESS = 'NARUDZBA_DOSTAVI_SUCCESS'
export const NARUDZBA_DOSTAVI_FAIL = 'NARUDZBA_DOSTAVI_FAIL'
export const NARUDZBA_DOSTAVI_RESET = 'NARUDZBA_DOSTAVI_RESET'