export const PROIZVOD_LIST_REQUEST = 'PROIZVOD_LIST_REQUEST'
export const PROIZVOD_LIST_SUCCESS = 'PROIZVOD_LIST_SUCCESS'
export const PROIZVOD_LIST_FAIL = 'PROIZVOD_LIST_FAIL'



export const PROIZVOD_DETALJI_REQUEST = 'PROIZVOD_DETALJI_REQUEST'
export const PROIZVOD_DETALJI_SUCCESS = 'PROIZVOD_DETALJI_SUCCESS'
export const PROIZVOD_DETALJI_FAIL = 'PROIZVOD_DETALJI_FAIL'



export const PROIZVOD_DELETE_REQUEST = 'PROIZVOD_DELETE_REQUEST'
export const PROIZVOD_DELETE_SUCCESS = 'PROIZVOD_DELETE_SUCCESS'
export const PROIZVOD_DELETE_FAIL = 'PROIZVOD_DELETE_FAIL'


export const PROIZVOD_KREIRAJ_REQUEST = 'PROIZVOD_KREIRAJ_REQUEST'
export const PROIZVOD_KREIRAJ_SUCCESS = 'PROIZVOD_KREIRAJ_SUCCESS'
export const PROIZVOD_KREIRAJ_FAIL = 'PROIZVOD_KREIRAJ_FAIL'
export const PROIZVOD_KREIRAJ_RESET = 'PROIZVOD_KREIRAJ_RESET'


export const PROIZVOD_AZURIRAJ_REQUEST = 'PROIZVOD_AZURIRAJ_REQUEST'
export const PROIZVOD_AZURIRAJ_SUCCESS = 'PROIZVOD_AZURIRAJ_SUCCESS'
export const PROIZVOD_AZURIRAJ_FAIL = 'PROIZVOD_AZURIRAJ_FAIL'
export const PROIZVOD_AZURIRAJ_RESET = 'PROIZVOD_AZURIRAJ_RESET'